source 'https://rubygems.org'


gem 'rails', '4.2.5'

gem 'rails-api'

gem 'spring', :group => :development


gem 'sqlite3'

gem 'pry-rails'
gem 'active_model_serializers'
gem 'rack-cors'
gem 'faker'
